name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ci-app:
    name: CI app
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Type checking
        run: yarn type-check
      - name: Testing
        run: yarn test
      - name: Linting
        run: yarn lint
